### PR TITLE
Support newer version of CC:tweaked

### PR DESCRIPTION
**Pull request by BRNSystems**
Changes gradle.properties to support 1.111.0

### CODE REVIEW

**Comment by Aranyalma2** [comment]
Somewhere at the [Ignore enchantments/attributes on the original item](https://github.com/cc-tweaked/CC-Tweaked/commit/94c864759d8ad98abaadc6c053edbc12e420af3d) commit the [polymer patch`s](https://github.com/PolymerPorts/cc-tweaked-patch) mixins (TurtleToolAccessor) went incompatible with CC:T later versions. (Before that commit there was a critical turtle tool equip bug on 1.20.5-6 branch, made the mod mostly unplayable)

Example for an error log:

```
[23:51:20] [main/ERROR]: Mixin apply for mod cc-tweaked-polymer-patch failed cc-tweaked-polymer-patch.mixins.json:TurtleToolAccessor from mod cc-tweaked-polymer-patch -> dan200.computercraft.shared.turtle.upgrades.TurtleTool: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching item:Lnet/minecraft/class_1799; in dan200/computercraft/shared/turtle/upgrades/TurtleTool for cc-tweaked-polymer-patch.mixins.json:TurtleToolAccessor from mod cc-tweaked-polymer-patch->@Accessor[FIELD_GETTER]::getItem()Lnet/minecraft/class_1799; [INJECT Applicator Phase -> cc-tweaked-polymer-patch.mixins.json:TurtleToolAccessor from mod cc-tweaked-polymer-patch -> Apply Accessors ->  -> Locate -> cc-tweaked-polymer-patch.mixins.json:TurtleToolAccessor from mod cc-tweaked-polymer-patch->@Accessor[FIELD_GETTER]::getItem()Lnet/minecraft/class_1799;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching item:Lnet/minecraft/class_1799; in dan200/computercraft/shared/turtle/upgrades/TurtleTool for cc-tweaked-polymer-patch.mixins.json:TurtleToolAccessor from mod cc-tweaked-polymer-patch->@Accessor[FIELD_GETTER]::getItem()Lnet/minecraft/class_1799; [INJECT Applicator Phase -> cc-tweaked-polymer-patch.mixins.json:TurtleToolAccessor from mod cc-tweaked-polymer-patch -> Apply Accessors ->  -> Locate -> cc-tweaked-polymer-patch.mixins.json:TurtleToolAccessor from mod cc-tweaked-polymer-patch->@Accessor[FIELD_GETTER]::getItem()Lnet/minecraft/class_1799;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at dan200.computercraft.shared.ModRegistry$TurtleUpgradeTypes.lambda$static$3(ModRegistry.java:396) ~[cc-tweaked-1.20.6-fabric-1.111.0.jar:?]
	at dan200.computercraft.shared.platform.PlatformHelperImpl$RegistryEntryImpl.register(PlatformHelperImpl.java:281) ~[cc-tweaked-1.20.6-fabric-1.111.0.jar:?]
	at dan200.computercraft.shared.platform.PlatformHelperImpl$RegistrationHelperImpl.register(PlatformHelperImpl.java:266) ~[cc-tweaked-1.20.6-fabric-1.111.0.jar:?]
	at dan200.computercraft.shared.ModRegistry.register(ModRegistry.java:569) ~[cc-tweaked-1.20.6-fabric-1.111.0.jar:?]
	at dan200.computercraft.shared.ComputerCraft.init(ComputerCraft.java:74) ~[cc-tweaked-1.20.6-fabric-1.111.0.jar:?]
	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(Unknown Source) ~[?:?]
	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy33.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) [fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric.jar:1.0.1]
```

**Comment by BRNSystems** [comment]
When I ran it in IntelliJ, it worked fine.
In game it crashed, because it did not find factory tools(had to download polyfactory) and now I got your crash

**Comment by BRNSystems** [comment]
It works now

**Comment by Patbox** [comment]
Didn't notice you updated this... oops. Going to go with my changes as I also fixed some other bugs. Through thanks for pointing the issue out!

**Pull request closed without merging**
